<a href="https://colab.research.google.com/github/VaibhavJain05/Machine-Learning-Vaibhav-Jain/blob/main/Linear_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np   
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
p1= "/content/drive/MyDrive/Linear regression/Linear_train.csv"
p2= "/content/drive/MyDrive/Linear regression/Linear_test.csv"

In [6]:
train_set= pd.read_csv(p1)
test_set= pd.read_csv(p2)

Linear regression

In [7]:
train_set

Unnamed: 0          A            B          C          D          E  \
0               0  -9.989516  1564.957586   8.199060  32.508797  19.464400   
1               1 -17.591800  1559.053039  12.302737 -36.351098   6.256406   
2               2 -28.321695  1305.900952 -35.681049  -9.039358 -45.519426   
3               3 -40.471241  1612.746996 -28.980454   2.137719 -34.767491   
4               4 -36.525271  1852.275617 -32.744347  -1.439526 -14.061837   
...           ...        ...          ...        ...        ...        ...   
49995       49995  38.882059  1829.766795  -9.597762  42.286077 -45.676532   
49996       49996 -29.570690  1467.757407  -2.581269   8.699766 -32.209400   
49997       49997 -26.656483  1081.812179  19.742925 -49.109287  -8.179490   
49998       49998  49.470595  1418.823031  14.854524  -6.995360  27.184947   
49999       49999 -25.982072  1679.672351 -34.735487 -16.517472   6.606794   

                 F          G          H            I  ...           L  \
0      1644.524093  26.100966  34.731954  4378.575414  ...  770.535311   
1      1640.834263  12.954212 -43.333128  4833.766813  ...  997.260070   
2      2039.003363  -0.154348  18.107957  4162.395297  ...  616.059291   
3      2757.469393  23.857472 -48.434183  4340.953927  ...  715.537625   
4      2138.422485  44.061988  33.336936  4099.453685  ...  629.221442   
...            ...        ...        ...          ...  ...         ...   
49995  2340.446842  44.758699 -49.232038  4561.096049  ...  931.215587   
49996  2065.685621  13.244693 -27.154067  4922.613361  ...  646.439398   
49997  1755.112415 -26.730046 -32.187078  4289.779346  ...  950.109763   
49998  1235.231487  34.556613 -33.790945  4119.297411  ...  742.735044   
49999  2375.299327  33.975192  -8.225393  4017.898569  ...  888.777601   

               M          N          O          P          Q          R  \
0      30.060441 -25.002361  11.892468 -34.329383  37.218423  -4.440530   
1      -1.329145  16.022086  42.972484  -7.372877  45.550946  37.576551   
2      -6.997085  27.846844  26.511376  19.323152 -35.807513  -5.913019   
3     -12.441561  47.883435  36.994884  30.783992  22.162383  16.465836   
4      10.992360 -47.143335  -8.296962  -8.086565  39.169726 -49.540056   
...          ...        ...        ...        ...        ...        ...   
49995 -19.667192  20.825892  18.055764 -40.074521  44.966776  30.681416   
49996  45.407497 -41.574684 -41.278010  34.484129  16.631234 -10.488980   
49997  -1.341077 -33.268738  32.604813 -17.198521 -29.136001  24.609231   
49998 -48.406474  -4.081799  20.777856 -49.422060 -31.251860 -27.546928   
49999  33.897617 -25.710304  27.512513  29.199493  29.509718 -47.344110   

               S          T         label  
0      29.075092  29.107896    311.232491  
1      12.926551 -32.565844   6393.112342  
2      15.046779 -34.332357   2601.046223  
3      41.435425  33.561233  13572.118106  
4     -32.518653 -36.320202  -5462.446898  
...          ...        ...           ...  
49995  38.376682  33.942225   9034.945727  
49996 -11.637358 -25.774032  -6345.178110  
49997  11.935784 -35.190456   1483.917022  
49998  38.121308 -10.588040  10720.139180  
49999  -3.357583 -48.462504   2185.127958  

[50000 rows x 22 columns]

In [8]:
test_set

Unnamed: 0          A            B          C          D          E  \
0              0  40.790740  1187.897579 -28.941991  43.498302  14.157983   
1              1  47.968749  1498.588679  24.922821 -38.979082  16.405452   
2              2   9.762564  1316.354415   1.170771  10.365178 -11.993156   
3              3   6.414629  1895.586749  44.496934 -49.677800 -24.825833   
4              4  -4.112012  1130.920162  19.103960  -8.741503 -28.589701   
...          ...        ...          ...        ...        ...        ...   
9995        9995 -37.802773  1204.712095  30.916166 -32.185868  -1.860028   
9996        9996  21.841410  1067.350891  -9.598592  13.545191   2.910106   
9997        9997 -34.734278  1630.673420  27.359399  -0.718695 -24.225154   
9998        9998 -30.752354  1610.117693 -37.652326 -46.959112  18.151935   
9999        9999  39.757972  1360.988948  -7.480509  27.155692  43.509194   

                F          G          H            I  ...           L  \
0     2536.000797 -34.181638 -14.940211  4746.739893  ...  707.727094   
1     1798.950305 -23.660484 -34.792328  4076.982013  ...  737.135391   
2     2714.382200  26.382837  27.442924  4178.719984  ...  940.732329   
3     2327.316373   1.406644  44.103008  4586.697737  ...  925.441952   
4     1299.418975  42.946135   4.758032  4809.536369  ...  797.953813   
...           ...        ...        ...          ...  ...         ...   
9995  1515.265232 -43.103776  12.911176  4865.716464  ...  877.773521   
9996  1286.431551 -49.542330  27.868152  4513.212740  ...  518.544504   
9997  1309.956055  36.839488 -40.966273  4747.087919  ...  948.924788   
9998  2489.587758 -33.802220 -11.550250  4912.443446  ...  656.905027   
9999  1700.776478   4.496912  42.373176  4579.120167  ...  582.145397   

              M          N          O          P          Q          R  \
0     21.030812 -44.606156  -9.625546  42.276162 -11.000471 -19.830564   
1    -17.860346  42.274026 -19.886483  16.337922   9.025313  27.760845   
2    -35.879432  23.837924   3.729191  33.564390  12.848880 -45.837834   
3    -19.409771  25.346975  -7.729920 -42.813516 -17.666168  35.506064   
4    -46.788081  43.876292  34.009303  34.061089 -30.182903 -41.188733   
...         ...        ...        ...        ...        ...        ...   
9995 -14.401216  -1.152501   9.371124 -16.953167   5.590761  27.769178   
9996  -4.202304  -6.779170   2.384596  20.661830  -7.804846  -3.170458   
9997 -31.628023  -5.662373 -45.441406 -33.063193 -23.153715  -7.089845   
9998 -48.696117 -20.709813 -27.404294  14.174336  40.169075  37.329627   
9999  28.458183 -47.300191 -19.032777 -15.959350 -10.118301  38.306081   

              S          T         label  
0     -5.529430 -28.154864   -163.522723  
1     21.484409 -24.206545   6484.664510  
2    -49.592176  36.688611   2393.818082  
3    -49.048652 -34.048583  -9397.072355  
4     26.828040 -22.476663  10487.323575  
...         ...        ...           ...  
9995 -42.025878 -46.347044  -7526.092452  
9996  39.886812 -17.630468   6133.716734  
9997 -25.366712  47.034834  -1404.204034  
9998 -27.968720 -18.475040   1972.371711  
9999  -2.826688 -38.647683  -6120.248772  

[10000 rows x 22 columns]

In [9]:
train = train_set.to_numpy() #converting datasets from csv to numpy arrays
test = test_set.to_numpy()

In [10]:
X= train[:,1:21]
print(X,"\n",X.shape)

[[  -9.98951633 1564.95758616    8.19906039 ...   -4.44053011
    29.07509189   29.10789613]
 [ -17.5918001  1559.05303891   12.30273704 ...   37.57655145
    12.92655138  -32.565844  ]
 [ -28.32169493 1305.90095196  -35.68104918 ...   -5.91301909
    15.04677873  -34.33235748]
 ...
 [ -26.65648272 1081.81217873   19.74292531 ...   24.60923107
    11.93578385  -35.19045552]
 [  49.47059508 1418.82303132   14.85452401 ...  -27.54692823
    38.12130809  -10.58803951]
 [ -25.98207155 1679.67235121  -34.7354873  ...  -47.34410994
    -3.35758254  -48.46250393]] 
 (50000, 20)


In [11]:
X1= test[:,1:21]
X1.shape


(10000, 20)

In [12]:
Y = train[:,21]
Y = np.vstack(Y)
print(Y, "\n",Y.shape)

[[  311.23249087]
 [ 6393.11234169]
 [ 2601.04622323]
 ...
 [ 1483.91702162]
 [10720.1391803 ]
 [ 2185.12795794]] 
 (50000, 1)


In [13]:
Y1= np.vstack(test[:,21])
Y1

array([[ -163.52272341],
       [ 6484.66451042],
       [ 2393.81808186],
       ...,
       [-1404.204034  ],
       [ 1972.37171111],
       [-6120.24877236]])

In [14]:
def mean_scale(X):   #applying mean normalization and using standard deviation in place of range
  X_mean= X.mean(axis=0)
  X_std= X.std(axis=0)
  X_scale = (X-X_mean)/(X_std)
  return(X_scale)


In [15]:
X_test= mean_scale(X1) #X1 is testing dataset
X_test.shape

(10000, 20)

In [16]:
X_train=mean_scale(X) #X is training dataset
print(X_train,X_train.shape)
     

[[-0.34799407  0.22031433  0.28511282 ... -0.15582334  1.0052814
   1.00876462]
 [-0.61114616  0.19984917  0.42713042 ...  1.29439989  0.44683234
  -1.12340336]
 [-0.98256011 -0.67757616 -1.23346387 ... -0.20664643  0.52015407
  -1.18447479]
 ...
 [-0.924919   -1.45426802  0.68461602 ...  0.8468317   0.41256961
  -1.21414073]
 [ 1.71021016 -0.28618815  0.51544114 ... -0.95334269  1.31811777
  -0.36359261]
 [-0.90157434  0.61791579 -1.20074042 ... -1.63664414 -0.1163058
  -1.67297842]] (50000, 20)


In [17]:
P0 = np.ones(X_train.shape[0])
P= np.vstack(P0)
print(P,P.shape)

[[1.]
 [1.]
 [1.]
 ...
 [1.]
 [1.]
 [1.]] (50000, 1)


In [18]:
Q0 = np.ones(X_test.shape[0])
Q= np.vstack(Q0)

In [19]:
X_Train1 = np.append(P,X_train,axis=1)   #adding bias inputs to the arrays
print(X_Train1)

[[ 1.         -0.34799407  0.22031433 ... -0.15582334  1.0052814
   1.00876462]
 [ 1.         -0.61114616  0.19984917 ...  1.29439989  0.44683234
  -1.12340336]
 [ 1.         -0.98256011 -0.67757616 ... -0.20664643  0.52015407
  -1.18447479]
 ...
 [ 1.         -0.924919   -1.45426802 ...  0.8468317   0.41256961
  -1.21414073]
 [ 1.          1.71021016 -0.28618815 ... -0.95334269  1.31811777
  -0.36359261]
 [ 1.         -0.90157434  0.61791579 ... -1.63664414 -0.1163058
  -1.67297842]]


In [20]:
X_Test1 = np.append(Q,X_test,axis=1)
X_Test1

array([[ 1.        ,  1.41899979, -1.10382181, ..., -0.69517339,
        -0.19489326, -0.97652993],
       [ 1.        ,  1.66716943, -0.02590781, ...,  0.96093801,
         0.74538325, -0.83992295],
       [ 1.        ,  0.34624395, -0.65815272, ..., -1.60018835,
        -1.72859476,  1.26697399],
       ...,
       [ 1.        , -1.19217223,  0.43234797, ..., -0.251815  ,
        -0.88537381,  1.62494049],
       [ 1.        , -1.05450277,  0.36103178, ...,  1.29391763,
        -0.97594245, -0.64162   ],
       [ 1.        ,  1.38329327, -0.50329733, ...,  1.32789681,
        -0.10081834, -1.33956845]])

Gradient decsent


In [21]:
def linear_regression(A,B,C,iterations,alpha):
   m=len(A)
   theta0 = np.zeros(A.shape[1])
   theta = np.vstack(theta0)
   for i in range(iterations) :
     h_x = np.dot(A, theta)
     error = h_x - B
     cost = (1/(2*m))*np.sum(np.square(error))
     grad= (1/m)*np.dot((A).T, error)
     theta = theta - (alpha)*(grad)
     print(cost)
   D = np.dot(C, theta)
   return D
   #A= input matrix
   #B= output matrix
   #C= testing matrix

In [34]:
LR=linear_regression( X_Train1,Y,X_Test1,3000,0.1 )
LR


13398388.663990432
10860037.235206382
8802782.266412493
7135416.122479755
5784027.261480227
4688719.419614049
3800953.2848571157
3081392.5195183735
2498158.419099094
2025415.6634483165
1642226.335064155
1331621.3036866519
1079847.7367838887
875759.3220531582
710322.1288870638
576214.1729899088
467500.9104937695
379372.2601378449
307929.4843053588
250012.47344834838
203059.77209259156
164995.137936174
134135.60313123162
109116.96100146133
88833.37459586571
72388.4299615636
59055.46466511805
48245.41345033632
39480.7462592706
32374.343963662606
26612.37604898871
21940.42187960915
18152.22092459737
15080.553819132194
12589.850545072062
10570.198525064687
8932.485431302372
7604.461763044768
6527.5489748984855
5654.251946486336
4946.061336998746
4371.753051111862
3906.009616922181
3528.302520704714
3221.9860886022702
2973.562863296103
2772.0880088181884
2608.686424896098
2476.161235839111
2368.676358646154
2281.499129582854
2210.791622886827
2153.44144699765
2106.924547990553
2069.193963898

array([[ -233.64054661],
       [ 6422.72630517],
       [ 2322.77488195],
       ...,
       [-1498.64989629],
       [ 1907.98807241],
       [-6201.64051423]])

In [35]:
diff = LR-Y1
diff

array([[-70.1178232 ],
       [-61.93820524],
       [-71.04319991],
       ...,
       [-94.44586229],
       [-64.3836387 ],
       [-81.39174188]])

In [36]:
error_rms = (np.sum((diff)**2)/(2*len(Y1)))**(1/2)
error_rms 

52.86385049917084