<a href="https://colab.research.google.com/github/VaibhavJain05/Machine-Learning-Vaibhav-Jain/blob/main/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np   
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
p1="/content/drive/MyDrive/Logistic Regression/emnist-letters-train.csv"
p2="/content/drive/MyDrive/Logistic Regression/emnist-letters-test.csv"

In [4]:
train_set= pd.read_csv(p1, header=None)
test_set= pd.read_csv(p2, header=None)

In [5]:
train_set


0    1    2    3    4    5    6    7    8    9    ...  775  776  777  \
0       23    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        7    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2       16    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3       15    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4       23    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
88795    1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88796   21    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88797    1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88798   23    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88799   12    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       778  779  780  781  782  783  784  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
88795    0    0    0    0    0    0    0  
88796    0    0    0    0    0    0    0  
88797    0    0    0    0    0    0    0  
88798    0    0    0    0    0    0    0  
88799    0    0    0    0    0    0    0  

[88800 rows x 785 columns]

In [6]:
test_set


0    1    2    3    4    5    6    7    8    9    ...  775  776  777  \
0        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
14795   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14796   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14797   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14798   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14799   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       778  779  780  781  782  783  784  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
14795    0    0    0    0    0    0    0  
14796    0    0    0    0    0    0    0  
14797    0    0    0    0    0    0    0  
14798    0    0    0    0    0    0    0  
14799    0    0    0    0    0    0    0  

[14800 rows x 785 columns]

In [7]:
train = train_set.to_numpy() #converting datasets from csv to numpy arrays
test = test_set.to_numpy()

In [8]:
m = train.shape[0]

In [9]:
mt = test.shape[0]
mt

14800

In [10]:
x = (train[:,1:])/255   #training sets
x.shape

(88800, 784)

In [11]:
xt = (test[:,1:])/255  #testing sets
xt.shape

(14800, 784)

In [12]:
a = np.vstack(np.ones(m))
X= np.append(a,x,axis=1)

In [13]:
at = np.vstack(np.ones(mt))
Xt= np.append(at,xt,axis=1)

In [14]:
y = train[:,0]  #training output
Y= np.vstack(y)

In [15]:
yt= test[:,0]   #testing output
Yt = np.vstack(yt)

In [16]:
Z= np.zeros((m,26)) #creating a zero matrix 
Z.shape

(88800, 26)

In [17]:
for i in range(m):  #applying one vs all 
  Z[i][Y[i]-1] = 1
  i+=1
Z


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

gradient descent

In [18]:
def lr(A,B,C,iterations,alpha):
  theta = np.zeros((A.shape[1], B.shape[1]))
  for i in range(iterations):
    z= A@theta
    h_x = 1/(1+ np.exp(-z))
    cost = (-1/m)*(np.sum(B*(np.log(h_x)) + (1-B)*(np.log(1-h_x))))
    grad = (1/m)*(np.dot(A.T,(h_x -B)))
    theta = theta - (alpha*grad)
    print(cost)
  D= 1/(1+ np.exp(-C@theta))
  return D

In [19]:
Y_pred = lr(X,Z,Xt,1000,0.9)
Y_pred

18.021826694558612
17.966727679902558
16.00118077603134
14.036607317405414
12.074324722404963
10.118106524022185
8.180804083468898
6.316549066719666
4.725017337217947
3.646361146631257
3.1521233578901664
2.941904512486611
2.8419467707544235
2.787684486946186
2.7483131626920145
2.7150362512757513
2.6857227481326427
2.659493873395915
2.635838168740178
2.614337704413044
2.5946780747263074
2.576599597437452
2.5598956593810365
2.544395113176219
2.529956214321016
2.5164595890478583
2.503803415407477
2.491900295399364
2.4806742313863204
2.4700590283048323
2.4599965050928114
2.4504355375811824
2.441330962469096
2.4326429082053713
2.4243360619891403
2.41637915103165
2.4087444104649736
2.4014071665707353
2.394345434324023
2.3875395854901145
2.380972042582089
2.374627021075606
2.368490299164592
2.3625490223489667
2.3567915323337627
2.3512072213216055
2.3457864057569195
2.3405202184387632
2.3354005153466333
2.330419795628383
2.3255711323805577
2.3208481128185556
2.3162447862585007
2.31175561881306

array([[1.58977692e-01, 9.75432783e-03, 5.38946881e-05, ...,
        1.50572908e-03, 6.71794026e-03, 7.29379928e-07],
       [1.43020374e-01, 4.49456037e-03, 4.24058497e-09, ...,
        3.84443036e-01, 7.53961518e-03, 5.74967939e-04],
       [3.14718913e-01, 2.67192603e-05, 6.68412067e-02, ...,
        1.18747107e-04, 2.22496003e-05, 1.12917480e-03],
       ...,
       [1.94190572e-02, 1.14313044e-01, 9.29881784e-05, ...,
        4.95464509e-05, 2.81380583e-06, 5.65918497e-04],
       [1.50008121e-02, 4.47777839e-02, 6.76119694e-03, ...,
        3.67248252e-03, 3.39707563e-03, 3.90670387e-03],
       [2.67806929e-01, 1.59410677e-03, 3.30566707e-02, ...,
        1.30282526e-02, 6.07176038e-05, 1.53366091e-03]])

In [20]:
max_value= Y_pred.max(axis=1)
for i in range(mt):
  for j in range(26):
    if Y_pred[i][j]== max_value[i] :
      Y_pred[i][j]=1
    else :
      Y_pred[i][j]=0
print(Y_pred)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [21]:
w = np.empty_like(Yt)

In [22]:
for i in range(mt):
  for j in range(26):
    if Y_pred[i][j]==1:
      w[i]= j+1
print(w)


[[ 5]
 [24]
 [ 1]
 ...
 [19]
 [10]
 [ 1]]


In [23]:
d=w-Yt
d

array([[  4],
       [ 23],
       [  0],
       ...,
       [  0],
       [ -9],
       [-18]])

In [24]:
g=0
for i in range(mt):
  if d[i]==0:
    g+=1
print(g)

10294


In [25]:
acc = (g/mt)*100
acc

69.55405405405405