<a href="https://colab.research.google.com/github/VaibhavJain05/Machine-Learning-Vaibhav-Jain/blob/main/neural_network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
import pandas as pd
import matplotlib as plt

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [5]:
p1="/content/drive/MyDrive/Logistic Regression/emnist-letters-train.csv"
p2="/content/drive/MyDrive/Logistic Regression/emnist-letters-test.csv"

In [6]:
train_set= pd.read_csv(p1,header= None)
test_set= pd.read_csv(p2,header=None)

In [7]:
train_set

0    1    2    3    4    5    6    7    8    9    ...  775  776  777  \
0       23    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        7    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2       16    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3       15    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4       23    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
88795    1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88796   21    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88797    1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88798   23    0    0    0    0    0    0    0    0    0  ...    0    0    0   
88799   12    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       778  779  780  781  782  783  784  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
88795    0    0    0    0    0    0    0  
88796    0    0    0    0    0    0    0  
88797    0    0    0    0    0    0    0  
88798    0    0    0    0    0    0    0  
88799    0    0    0    0    0    0    0  

[88800 rows x 785 columns]

In [8]:
test_set

0    1    2    3    4    5    6    7    8    9    ...  775  776  777  \
0        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
1        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
2        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
3        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
4        1    0    0    0    0    0    0    0    0    0  ...    0    0    0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
14795   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14796   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14797   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14798   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   
14799   19    0    0    0    0    0    0    0    0    0  ...    0    0    0   

       778  779  780  781  782  783  784  
0        0    0    0    0    0    0    0  
1        0    0    0    0    0    0    0  
2        0    0    0    0    0    0    0  
3        0    0    0    0    0    0    0  
4        0    0    0    0    0    0    0  
...    ...  ...  ...  ...  ...  ...  ...  
14795    0    0    0    0    0    0    0  
14796    0    0    0    0    0    0    0  
14797    0    0    0    0    0    0    0  
14798    0    0    0    0    0    0    0  
14799    0    0    0    0    0    0    0  

[14800 rows x 785 columns]

In [9]:
train = train_set.to_numpy() #converting datasets from csv to numpy arrays
test = test_set.to_numpy()

In [10]:
x=(train[:,1:])/255
xt=(test[:,1:])/255

In [11]:
m=x.shape[0]
mt=xt.shape[0]

In [12]:
y=train[:,0]
yt=test[:,0]

In [13]:
#applying one vs all 
def one_vs_all(m):
  Z= np.zeros((m,26))
  for i in range(m):  
    Z[i][y[i]-1] = 1
    i+=1
  return Z
yp=one_vs_all(m)
ypt=one_vs_all(mt)

In [14]:
def sigm_(a):
  return 1/(1+np.exp(-a))

In [15]:
def sigm_derv(a):
  return a*(1-a)

In [16]:
epsilon = np.random.random(1)[0]

In [17]:
def nn(x,iterations,alpha,m,c):
  #gradient descent
  #paramaters
  theta1=np.random.rand(26,x.shape[1])*(2*epsilon) - epsilon
  bias1=np.random.rand(26,1)*(2*epsilon) - epsilon
  theta2=np.random.rand(26,26)*(2*epsilon) - epsilon
  bias2=np.random.rand(26,1)*(2*epsilon) - epsilon
  theta3=np.random.rand(26,26)*(2*epsilon) - epsilon
  bias3=np.random.rand(26,1)*(2*epsilon) - epsilon
  for i in range(iterations):
    #forward propagation
    Z2 = theta1@(x.T) + bias1
    A2 = sigm_(Z2)
    Z3 = theta2@(A2) + bias2
    A3 = sigm_(Z3)
    Z4 = theta3@(A3) + bias3
    h_x = sigm_(Z4)
    
    #back propagation
    dZ4 = h_x - c.T
    dtheta3 = dZ4@(A3.T)
    dbias3 = np.sum(dZ4)
    dZ3 = ((theta3.T)@(dZ4))*(sigm_derv(A3))
    dtheta2 = dZ3@(A2.T)
    dbias2 = np.sum(dZ3)
    dZ2 = ((theta2.T)@(dZ3))*(sigm_derv(A2))
    dtheta1 = dZ3@(x)
    dbias1  = np.sum(dZ2)
 

    #updating parameters
    theta1 -= (alpha/m)*(dtheta1)
    bias1 -= (alpha/m)*(dbias1)    
    theta2 -= (alpha/m)*(dtheta2)  
    bias2 -= (alpha/m)*(dbias2)  
    theta3 -= (alpha/m)*(dtheta3)
    bias3 -= (alpha/m)*(dbias3)
    
    cost=(-1/m)*(np.sum(c.T*(np.log(h_x)) + (1-c.T)*(np.log(1-h_x))))
    if i%10==0:
      print(cost)
  return theta1,bias1,theta2,bias2,theta3,bias3

In [18]:
q1,b1,q2,b2,q3,b3= nn(xt,300,0.7,mt,ypt)
#forward propagation on test
Z2 = q1@(xt.T) + b1
A2 = sigm_(Z2)
Z3 = q2@(A2) + b2
A3 = sigm_(Z3)
Z4 = q3@(A3) + b3
y_pred= sigm_(Z4)

22.126171917383115
4.319512152641521
4.2683537113626855
4.267752656629355
4.2671131327408345
4.266422740652387
4.2656674594576325
4.264831111645037
4.263894859708672
4.2628367890399055
4.261631489177435
4.260248873313286
4.258652017819839
4.2568039886356575
4.254700268712421
4.25239605684181
4.250016009025407
4.24774908812101
4.245789962169109
4.244209361965253
4.242976810188034
4.242031064223887
4.241308065070565
4.240751919547732
4.240318556244973
4.239975432282542
4.239699315638564
4.239473721571446
4.239286816950567
4.239129942484086


In [19]:
y_pred

array([[0.03492008, 0.03564416, 0.04924524, ..., 0.04316394, 0.04531793,
        0.04678616],
       [0.03250755, 0.03437881, 0.03543187, ..., 0.03543976, 0.03482255,
        0.03491744],
       [0.03199668, 0.0387023 , 0.04307866, ..., 0.04010308, 0.04258178,
        0.04248133],
       ...,
       [0.03700104, 0.03610231, 0.04338647, ..., 0.03905783, 0.041818  ,
        0.04160514],
       [0.03534436, 0.03908615, 0.0404315 , ..., 0.03960244, 0.03784356,
        0.04074414],
       [0.03877985, 0.03607348, 0.03848389, ..., 0.03691856, 0.03857934,
        0.03971442]])

In [20]:
Y_P=y_pred.T

In [21]:
max_value= Y_P.max(axis=1)
for i in range(mt):
  for j in range(26):
    if Y_P[i][j]== max_value[i] :
      Y_P[i][j]=1
    else :
      Y_P[i][j]=0
print(Y_P)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]]


In [22]:
w = np.empty_like(yt)
for i in range(mt):
  for j in range(26):
    if Y_P[i][j]==1:
      w[i]= j+1
print(w)

[ 8 12  1 ... 21  1  1]


In [23]:
d= w-yt
g=0
for i in range(mt):
  if d[i]==0:
    g+=1
acc=(g/mt)*100
acc

4.3108108108108105